/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorPicker: typeof import('primevue/colorpicker')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Testing: typeof import('./src/components/Testing.vue')['default']
  }
}
